stages:
  - test

test:
  stage: test
  image: php:8.4-cli
  before_script:
    - apt-get update -yqq && apt-get install -yqq git unzip libzip-dev
    - docker-php-ext-install zip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer update --prefer-dist --no-interaction --no-progress
  script:
    - vendor/bin/phpunit
